// ==========================
// THIS FILE IS AUTOGENERATED
// ==========================

#ifndef U_{s}_H
#define U_{s}_H
 
#ifdef __cplusplus
extern "C" {{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Types
{s}

// Method types
{s}

// Methods
{s}

#ifdef __cplusplus
}}
#endif

#endif // U_{s}_H
